// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var MainElm = require("./Main.elm");
var TreeSitter = require("tree-sitter");
var TreeSitterElm = require("tree-sitter-elm");

var elmWorker = MainElm;

var parser = new TreeSitter();

parser.setLanguage(TreeSitterElm);

var source = "\nimport World exposing (Hello)\n";

var parsed = parser.parse(source);

((console.log(parsed.rootNode.child(0).child(2).namedChildren)));

exports.elmWorker = elmWorker;
exports.parser = parser;
exports.source = source;
exports.parsed = parsed;
/* elmWorker Not a pure module */
